version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: braintree
    versions:
    - 3.2.0
    - 3.2.1
    - 3.2.2
  - dependency-name: marked
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.6
  - dependency-name: slug
    versions:
    - 4.0.2
    - 4.0.3
  - dependency-name: express-validator
    versions:
    - 6.10.0
    - 6.9.2
  - dependency-name: json2csv
    versions:
    - 5.0.5
